from typing import List, Protocol
from common_types import DNSRecord

class EmailDeliveryPort(Protocol):
    def create_subdomain(self, subdomain: str, domain: str) -> List[DNSRecord]: ...
    def delete_subdomain(self, subdomain: str, domain: str) -> bool: ...
    def subdomain_exists(self, subdomain: str, domain: str) -> bool: ...
    def verify_domain(self, full_domain: str) -> bool: ...
    def create_user(self, local_part: str, domain: str) -> str: ...
    def delete_user(self, local_part: str, domain: str) -> bool: ...
    def get_users(self, domain: str) -> List[str]: ...