class DomainAccessError(Exception): ...
class SubdomainCreationError(Exception): ...
class DomainVerificationError(Exception): ...
class UserCreationError(Exception): ...
class UserNotFoundError(Exception): ...