
from typing import List, Protocol
from common_types import DNSRecord

class DnsPort(Protocol):
    def create_records(self, domain: str, subdomain: str, records: List[DNSRecord]) -> bool: ...
    def delete_records(self, domain: str, subdomain: str) -> bool: ...
    def exists_records(self, domain: str, subdomain: str) -> bool: ...